INSERT INTO country (code, name) VALUES ('AF', 'Afghanistan');
INSERT INTO country (code, name) VALUES ('AL', 'Albania');
INSERT INTO country (code, name) VALUES ('DZ', 'Algeria');
INSERT INTO country (code, name) VALUES ('AS', 'American Samoa');
INSERT INTO country (code, name) VALUES ('AD', 'Andorra');
INSERT INTO country (code, name) VALUES ('AO', 'Angola');
INSERT INTO country (code, name) VALUES ('AI', 'Anguilla');
INSERT INTO country (code, name) VALUES ('AQ', 'Antarctica');
INSERT INTO country (code, name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country (code, name) VALUES ('AR', 'Argentina');
INSERT INTO country (code, name) VALUES ('AM', 'Armenia');
INSERT INTO country (code, name) VALUES ('AW', 'Aruba');
INSERT INTO country (code, name) VALUES ('AU', 'Australia');
INSERT INTO country (code, name) VALUES ('AT', 'Austria');
INSERT INTO country (code, name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country (code, name) VALUES ('BS', 'Bahamas');
INSERT INTO country (code, name) VALUES ('BH', 'Bahrain');
INSERT INTO country (code, name) VALUES ('BD', 'Bangladesh');
INSERT INTO country (code, name) VALUES ('BB', 'Barbados');
INSERT INTO country (code, name) VALUES ('BY', 'Belarus');
INSERT INTO country (code, name) VALUES ('BE', 'Belgium');
INSERT INTO country (code, name) VALUES ('BZ', 'Belize');
INSERT INTO country (code, name) VALUES ('BJ', 'Benin');
INSERT INTO country (code, name) VALUES ('BM', 'Bermuda');
INSERT INTO country (code, name) VALUES ('BT', 'Bhutan');
INSERT INTO country (code, name) VALUES ('BO', 'Bolivia, Plurinational State of');
INSERT INTO country (code, name) VALUES ('BR', 'Brazil');
INSERT INTO country (code, name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country (code, name) VALUES ('BG', 'Bulgaria');
INSERT INTO country (code, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country (code, name) VALUES ('BI', 'Burundi');
INSERT INTO country (code, name) VALUES ('KH', 'Cambodia');
INSERT INTO country (code, name) VALUES ('CM', 'Cameroon');
INSERT INTO country (code, name) VALUES ('CA', 'Canada');
INSERT INTO country (code, name) VALUES ('CV', 'Cape Verde');
INSERT INTO country (code, name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country (code, name) VALUES ('CF', 'Central African Republic');
INSERT INTO country (code, name) VALUES ('TD', 'Chad');
INSERT INTO country (code, name) VALUES ('CL', 'Chile');
INSERT INTO country (code, name) VALUES ('CN', 'China');
INSERT INTO country (code, name) VALUES ('CO', 'Colombia');
INSERT INTO country (code, name) VALUES ('KM', 'Comoros');
INSERT INTO country (code, name) VALUES ('CG', 'Congo');
INSERT INTO country (code, name) VALUES ('CD', 'Congo, the Democratic Republic of the');
INSERT INTO country (code, name) VALUES ('CR', 'Costa Rica');
INSERT INTO country (code, name) VALUES ('HR', 'Croatia');
INSERT INTO country (code, name) VALUES ('CU', 'Cuba');
INSERT INTO country (code, name) VALUES ('CY', 'Cyprus');
INSERT INTO country (code, name) VALUES ('CZ', 'Czech Republic');
INSERT INTO country (code, name) VALUES ('DK', 'Denmark');
INSERT INTO country (code, name) VALUES ('DJ', 'Djibouti');
INSERT INTO country (code, name) VALUES ('DM', 'Dominica');
INSERT INTO country (code, name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country (code, name) VALUES ('EC', 'Ecuador');
INSERT INTO country (code, name) VALUES ('EG', 'Egypt');
INSERT INTO country (code, name) VALUES ('SV', 'El Salvador');
INSERT INTO country (code, name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country (code, name) VALUES ('ER', 'Eritrea');
INSERT INTO country (code, name) VALUES ('EE', 'Estonia');
INSERT INTO country (code, name) VALUES ('ET', 'Ethiopia');
INSERT INTO country (code, name) VALUES ('FI', 'Finland');
INSERT INTO country (code, name) VALUES ('FR', 'France');
INSERT INTO country (code, name) VALUES ('DE', 'Germany');
INSERT INTO country (code, name) VALUES ('GH', 'Ghana');
INSERT INTO country (code, name) VALUES ('GR', 'Greece');
INSERT INTO country (code, name) VALUES ('GT', 'Guatemala');
INSERT INTO country (code, name) VALUES ('IN', 'India');
INSERT INTO country (code, name) VALUES ('ID', 'Indonesia');
INSERT INTO country (code, name) VALUES ('IR', 'Iran');
INSERT INTO country (code, name) VALUES ('IQ', 'Iraq');
INSERT INTO country (code, name) VALUES ('IE', 'Ireland');
INSERT INTO country (code, name) VALUES ('IL', 'Israel');
INSERT INTO country (code, name) VALUES ('IT', 'Italy');
INSERT INTO country (code, name) VALUES ('JP', 'Japan');
INSERT INTO country (code, name) VALUES ('JO', 'Jordan');
INSERT INTO country (code, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country (code, name) VALUES ('KE', 'Kenya');
INSERT INTO country (code, name) VALUES ('KP', 'North Korea');
INSERT INTO country (code, name) VALUES ('KR', 'South Korea');
INSERT INTO country (code, name) VALUES ('KW', 'Kuwait');
INSERT INTO country (code, name) VALUES ('LA', 'Laos');
INSERT INTO country (code, name) VALUES ('LV', 'Latvia');
INSERT INTO country (code, name) VALUES ('LB', 'Lebanon');
INSERT INTO country (code, name) VALUES ('LY', 'Libya');
INSERT INTO country (code, name) VALUES ('LT', 'Lithuania');
INSERT INTO country (code, name) VALUES ('LU', 'Luxembourg');
INSERT INTO country (code, name) VALUES ('MY', 'Malaysia');
INSERT INTO country (code, name) VALUES ('MV', 'Maldives');
INSERT INTO country (code, name) VALUES ('ML', 'Mali');
INSERT INTO country (code, name) VALUES ('MT', 'Malta');
INSERT INTO country (code, name) VALUES ('MX', 'Mexico');
INSERT INTO country (code, name) VALUES ('MC', 'Monaco');
INSERT INTO country (code, name) VALUES ('MN', 'Mongolia');
INSERT INTO country (code, name) VALUES ('MA', 'Morocco');
INSERT INTO country (code, name) VALUES ('MZ', 'Mozambique');
INSERT INTO country (code, name) VALUES ('MM', 'Myanmar');
INSERT INTO country (code, name) VALUES ('NA', 'Namibia');
INSERT INTO country (code, name) VALUES ('NP', 'Nepal');
INSERT INTO country (code, name) VALUES ('NL', 'Netherlands');
INSERT INTO country (code, name) VALUES ('NZ', 'New Zealand');
INSERT INTO country (code, name) VALUES ('NG', 'Nigeria');
INSERT INTO country (code, name) VALUES ('NO', 'Norway');
INSERT INTO country (code, name) VALUES ('OM', 'Oman');
INSERT INTO country (code, name) VALUES ('PK', 'Pakistan');
INSERT INTO country (code, name) VALUES ('PA', 'Panama');
INSERT INTO country (code, name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO country (code, name) VALUES ('PE', 'Peru');
INSERT INTO country (code, name) VALUES ('PH', 'Philippines');
INSERT INTO country (code, name) VALUES ('PL', 'Poland');
INSERT INTO country (code, name) VALUES ('PT', 'Portugal');
INSERT INTO country (code, name) VALUES ('QA', 'Qatar');
INSERT INTO country (code, name) VALUES ('RO', 'Romania');
INSERT INTO country (code, name) VALUES ('RU', 'Russia');
INSERT INTO country (code, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country (code, name) VALUES ('SG', 'Singapore');
INSERT INTO country (code, name) VALUES ('ZA', 'South Africa');
INSERT INTO country (code, name) VALUES ('ES', 'Spain');
INSERT INTO country (code, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO country (code, name) VALUES ('SE', 'Sweden');
INSERT INTO country (code, name) VALUES ('CH', 'Switzerland');
INSERT INTO country (code, name) VALUES ('SY', 'Syria');
INSERT INTO country (code, name) VALUES ('TW', 'Taiwan');
INSERT INTO country (code, name) VALUES ('TH', 'Thailand');
INSERT INTO country (code, name) VALUES ('TR', 'Turkey');
INSERT INTO country (code, name) VALUES ('UA', 'Ukraine');
INSERT INTO country (code, name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO country (code, name) VALUES ('GB', 'United Kingdom');
INSERT INTO country (code, name) VALUES ('US', 'United States');
INSERT INTO country (code, name) VALUES ('VN', 'Vietnam');
INSERT INTO country (code, name) VALUES ('YE', 'Yemen');
INSERT INTO country (code, name) VALUES ('ZW', 'Zimbabwe');
